from collections import OrderedDict
import csv
import logging
from oncotator.output.OutputRenderer import OutputRenderer


class GeneListOutputRenderer(OutputRenderer):
    """
     Render segments to a list of genes with the segment annotations attached to each gene.

     For example:
     input annotated segments:

     chr    start   end genes   annotation1 annotation2
     1  100 10000000    FAKE1,FAKE2 3   foo
     3  120 12000000    DUMMY1  5   bar

     output gene list generated by this class:

     gene   annotation1 annotation2
     FAKE1  3   foo
     FAKE2  3   foo
     DUMMY1 5   bar

    More realistic example output:
        gene segment_contig segment_start  segment_end  segment_mean    segment_call

    A gene can be listed multiple times if broken up by two separate segments.

    IMPORTANT: This class only supports the rendering of segments.

    This class uses more RAM than most of the other OutputRenderers and RAM usage will scale up with the number of genes.


    """
    def __init__(self, filename, configFile="", other_options=None):
        self._filename = filename


    def renderMutations(self, segments, metadata=None, comments=None):
        """Render segments into a gene list as described in the docs for this class.

        :param segments: iterable of MutationData
        :param metadata:
        :param comments:
        """

        if metadata is None:
            metadata = OrderedDict()

        if comments is None:
            comments = []

        fp = file(self._filename, 'w')
        for c in comments:
            fp.write("## " + c + "\n")

        # TODO: Define constant for "genes", and other annotations
        headers = ["gene", "segment_contig", "segment_start", "segment_end", "segment_mean", "segment_call"]
        gene_to_segment_dict = dict()
        annotations = []
        i = 0
        for i, seg in enumerate(segments):
            if len(annotations) == 0:
                annotations = seg.keys()
            gene_list = seg['genes'].split(",")
            for g in gene_list:
                gene_to_segment_dict[g] = seg


        all_genes_seen = sorted(gene_to_segment_dict.keys())
        if i == 0:
            logging.getLogger(__name__).info("No segments given.  There will be no genes in the list.")

        writer = csv.DictWriter(fp, headers, delimiter="\t", lineterminator="\n", extrasaction="ignore")

        headers.extend(sorted(annotations))
        writer.writeheader()
        for gene in all_genes_seen:
            # This next line may be slow...
            line_dict = dict()
            line_dict["gene"] = gene
            line_dict.update(gene_to_segment_dict[gene])
            del line_dict['genes']
            writer.writerow(line_dict)

        fp.close()


