
class VariantClassification(object):
    """ Stores the names and values of a variant classification.
    """
    INTRON = "Intron"
    FIVE_PRIME_UTR = "5'UTR"
    THREE_PRIME_UTR = "3'UTR"
    IGR = "IGR"
    FIVE_PRIME_PRIME_FLANK = "5'Flank"
    THREE_PRIME_PRIME_FLANK = "3'Flank"
    MISSENSE = "Missense_Mutation"
    NONSENSE = "Nonsense_Mutation"
    NONSTOP = "Nonstop_Mutation"
    SILENT = "Silent"
    SPLICE_SITE = "Splice_Site"
    IN_FRAME_DEL = "In_Frame_Del"
    IN_FRAME_INS = "In_Frame_Ins"
    FRAME_SHIFT_INS = "Frame_Shift_Ins"
    FRAME_SHIFT_DEL = "Frame_Shift_Del"
    START_CODON_SNP = "Start_Codon_SNP"
    START_CODON_INS = "Start_Codon_Ins"
    START_CODON_DEL = "Start_Codon_Del"
    STOP_CODON_INS = "Stop_Codon_Ins"
    STOP_CODON_DEL = "Stop_Codon_Del"
    # Note: A STOP_CODON_SNP is a nonstop mutation
    DE_NOVO_START_IN_FRAME = "De_novo_Start_InFrame"
    DE_NOVO_START_OUT_FRAME = "De_novo_Start_OutOfFrame"
    RNA = "RNA"

    VT_INS = "INS"
    VT_DEL = "DEL"
    VT_SNP = "SNP"

    def __init__(self):
        self._vc_primary = ""
        self._vc_secondary = ""
        self._transcript_id = ""
        self._alt_codon = ""
        self._ref_codon = ""
        self._ref_aa = ""
        self._ref_protein_start = ""
        self._ref_protein_end = ""
        self._alt_aa = ""
        self._alt_protein_start = ""
        self._alt_protein_end = ""

